### ISSUE TITLE
Is this github being maintained? 

### ISSUE THREAD

**Issue by GitKike98** [python-hyper/hyper#436]
> title.

**Comment by phillmac** [comment]
nope

**Comment by sethmlarson** [comment]
No this project is no longer maintained, you should use an alternative like HTTPX for a high level HTTP/2 client.

**Comment by seighail3** [comment]
> No this project is no longer maintained, you should use an alternative like HTTPX for a high level HTTP/2 client.

It doesnt work with proxies
